<?php

namespace FT\WebsiteBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllNews()
    {
        $qb = $this->createQueryBuilder('n');

        return $qb
            ->getQuery()
            ->getResult();

    }

}
