ft_website_homepage:
    path:     /
    defaults: { _controller: FTWebsiteBundle:Default:index }

ft_website_news_home:
    path:     /news/{page}
    defaults:
        _controller: FTWebsiteBundle:News:index
        page:        1
    requirements:
        page: \d*

ft_website_news_view:
    path:     /news/view/{id}
    defaults:
        _controller: FTWebsiteBundle:News:view
    requirements:
        id: \d+

ft_website_news_add:
    path:     admin/news/add
    defaults:
        _controller: FTWebsiteBundle:News:add

ft_website_news_edit:
    path:     admin/news/edit/{id}
    defaults:
        _controller: FTWebsiteBundle:News:edit
    requirements:
        id: \d+

ft_website_news_delete:
    path:     admin/news/delete/{id}
    defaults:
        _controller: FTWebsiteBundle:News:delete
    requirements:
        id: \d+

ft_website_dish_home:
    path:     /dish/{page}
    defaults:
        _controller: FTWebsiteBundle:Dish:index
        page:        1
    requirements:
        page: \d*

ft_website_dish_view:
    path:     /dish/view/{id}
    defaults:
        _controller: FTWebsiteBundle:Dish:view
    requirements:
        id: \d+

ft_website_dish_add:
    path:     admin/dish/add
    defaults:
        _controller: FTWebsiteBundle:Dish:add

ft_website_dish_edit:
    path:     admin/dish/edit/{id}
    defaults:
        _controller: FTWebsiteBundle:Dish:edit
    requirements:
        id: \d+

ft_website_dish_delete:
    path:     admin/dish/delete/{id}
    defaults:
        _controller: FTWebsiteBundle:Dish:delete
    requirements:
        id: \d+

ft_website_admin_home:
    path:     /admin
    defaults:
        _controller: FTWebsiteBundle:AdminHome:index

ft_website_admin_dish_index:
    path:     /admin/dish
    defaults:
        _controller: FTWebsiteBundle:AdminDish:index

ft_website_contact:
    path:     /contact
    defaults:
        _controller: FTWebsiteBundle:Contact:contact

ft_website_admin_news_index:
    path:     /admin/news
    defaults:
        _controller: FTWebsiteBundle:AdminNews:index